trigger:
  - main
pool:
  vmImage: ubuntu-latest
steps:
  - task: Bash@3
    inputs:
      targetType: 'inline'
      script: 'sh -c "$(curl -fsSL https://get.testcontainers.cloud/bash)"'
    env:
      TC_CLOUD_TOKEN: $(TC_CLOUD_TOKEN)
  # other task definitions such as maven/gradle/npm test
